import React, { useEffect } from 'react'
import NavBar from './NavBar'
import Signup from './Signup'
import { useState,useRef } from 'react'
import Login from './Login';
import Features from './Features';
import { useAuth } from './AuthContext';
import { useNavigate } from 'react-router-dom';
function Landing() {
  const navigate = useNavigate();
  const {auth,setAuth,loading} = useAuth();
  const [Login_clicked, setLogin_clicked] = useState(false);
  const handle_login_click = ()=>{
    setLogin_clicked(true);
  }
  useEffect(() => {
    if(!loading && auth.logged){
      navigate("/Dashboard");
    }
  }, [loading])
  
  const feature_ref = useRef();
  const handle_exp_click = ()=>{
    feature_ref.current?.scrollIntoView({behavior: "smooth"});
  }
  const [features, setfeatures] = useState([
{
"title": "Tailored Just for You",
"desc": "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here."
},
{
"title": "Learn at Your Own Pace",
"desc": "Expand answers only when you’re ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
},
{
"title": "Capture Your Insights",
"desc": "Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful."
},
{
"title": "Understand the Why Behind Answers",
"desc": "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic."
},
{
"title": "Save, Organize, and Revisit",
"desc": "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off."
},
{
"title": "Real-Time AI Feedback",
"desc": "Receive instant, actionable AI feedback on your answers to highlight strengths, address weaknesses, and provide improvement tips—enabling continuous, targeted growth after every practice session."
}
]);
  return (
    <div>
      <NavBar handle_login_click={handle_login_click} />
      <div className="panels text-white grid grid-cols-2 font-sans my-[20vh]">
      <div className='left-panel flex flex-col px-[13vw] gap-[1.4rem]'>
        <div className="heading text-[2.2rem] font-[700] w-[40vw]">Ace Your Next Interview</div>
        <div className="content text-[#FFFFFF80] text-[1.2rem] w-[28vw]">InterveuX is your AI-powered interview preparation companion. Practice real-world technical and behavioral 
          questions, get instant feedback, and track your progress — all in one place.</div>
        <div className = "button bg-[#6059bb] w-[13vw] px-4 py-2 my-[1rem] rounded-3xl text-[1.2rem] text-center hover:bg-[#433e85] transition-colors duration-500 delay-[40]" onClick={handle_exp_click}>
          Explore Features
        </div>
      </div>
      <div className='right-panel text-black w-[50%] m-auto my-[-3.5vh]'>
        {Login_clicked?<Login/>:<Signup/>}
      </div>
      </div>
      <div className='text-[2.2rem] font-[700] w-[40vw] text-white mt-[40vh] mx-[33vw]'>Features That Make You Shine</div>
      <div className="feautres mt-[10vh] mx-[10vw]" ref={feature_ref}>
        <Features/>
      </div>
      <div className="footer h-[5vh] bg-black mt-[10vh]"></div>
    </div>
  )
}

export default Landing
